// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0gryFpVJ8i8uE_KxYiUhYuKCQoJqqcbU',
    appId: '1:407957103785:web:7d9b55ab697e33a7c535b8',
    messagingSenderId: '407957103785',
    projectId: 'elas-promocoes',
    authDomain: 'elas-promocoes.firebaseapp.com',
    storageBucket: 'elas-promocoes.appspot.com',
    measurementId: 'G-G4WQ2ZBM98',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCt_DkEzP6lTENr9pgUWaZiZRXG5GPFVQ8',
    appId: '1:407957103785:android:36f3ad88fc8cea51c535b8',
    messagingSenderId: '407957103785',
    projectId: 'elas-promocoes',
    storageBucket: 'elas-promocoes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMbHZYVd9lureAhhY-pboftSWRixjVPKs',
    appId: '1:407957103785:ios:8caeac94e965e795c535b8',
    messagingSenderId: '407957103785',
    projectId: 'elas-promocoes',
    storageBucket: 'elas-promocoes.appspot.com',
    iosClientId: '407957103785-8bvd08lpkjc5g360rvmucii09gv5gtb7.apps.googleusercontent.com',
    iosBundleId: 'com.dnn.elasPromocoes',
  );
}
