name: Flutter Web

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - name: Install dependencies
        run: flutter pub get

      - name: Build Web
        run: flutter build web --release

      - name: Deploy
        run: |
          cd build/web
          git init
          git config --global user.email danilloilggner@gmail.com
          git config --global user.name danilloism
          git status
          git remote add origin https://${{secrets.TOKEN}}@github.com/danilloism/elas_promocoes_website.git
          git checkout -b master
          git add --all
          git commit -m "update"
          git push origin master -f